version: '3.3'

services:
  postgres:
    image: postgres:latest
    container_name: iaint_postgres
    environment:
      POSTGRES_DB: iaint_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: iaint123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


