# Generated by Django 5.0.6 on 2024-07-05 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mage',
            table='mage',
        ),
        migrations.AlterModelTable(
            name='magicaffinity',
            table='magic_affinity',
        ),
    ]
